version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_secret_pwd
      MYSQL_DATABASE: wordpress
    volumes:
      - wordpress_db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - wordpress_app_data:/var/www/html

volumes:
  wordpress_db_data:
  wordpress_app_data:
